### ISSUE TITLE
Release Date Formatting

### ISSUE THREAD

**Issue by Dev-Elie** [hrishi7/streamIt#28]
For easy readability,i would advise on rendering the dates as Full dates (**November 1, 1993**)  instead of Date strings (**1993-11-01** )

**Comment by ayangupta9** [comment]
[My PR](https://github.com/hrishi7/streamIt/pull/34#issue-987915388)
I did create a PR for the same. Here's hoping it gets merged. 
Ps: Newbie here, so any kind of remark would be highly appreciated
