### ISSUE TITLE
Movie & Title Page

### ISSUE THREAD

**Issue by Dikshatomarr** [hrishi7/streamIt#41]
Display some random movies/TV shows in a slider below the search option bar to make user experience better. 
![image](https://user-images.githubusercontent.com/91546745/176992134-48fe494e-5a51-4af5-850f-664bb167bd73.png)

**Comment by darkknight20032001** [comment]
I am gonna work on the issue

**Comment by mihir2226** [comment]
I want to work on this issue

**Comment by Ayushbajpai19** [comment]
I would like to work on this issue.
