### ISSUE TITLE
Suggestion: Make radio button for form and ask if person is over 18 years old

### ISSUE THREAD

**Issue by mbernardes19** [hrishi7/streamIt#5]
![image](https://user-images.githubusercontent.com/26047592/47733267-9cb92180-dc46-11e8-975f-50835144b866.png)

I guess this form would be better if there was a radio button to check if the person is grown-up. Also, the question could be "Are you over 18 years old?". I guess it would be more usual to ask like that.

**Comment by hrishi7** [comment]
Thanks for pointing out the issue i have added those things -)
